import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'Software Engineer',
    company: 'Reach Finance',
    logo: '/images/careers/reach.png',
    location: 'Jakarta, Indonesia',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2022-09',
    end_date: null,
    industry: 'financing',
    link: 'https://getreach.id',
  },
  {
    position: 'Software Engineer',
    company: 'Inarray',
    logo: '/images/careers/inarray.png',
    location: 'Jakarta, Indonesia',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-07',
    end_date: '2022-09',
    industry: 'software house',
    link: 'https://inarray.id',
  },
  {
    position: 'Frontend Developer',
    company: 'Capio',
    logo: '/images/careers/capio.png',
    location: 'Jakarta, Indonesia',
    location_type: 'Remote',
    type: 'Fulltime',
    start_date: '2021-01',
    end_date: '2021-07',
    industry: 'financing',
    link: 'https://capioteknologi.co.id',
  },
  {
    position: 'Full Stack Developer',
    company: 'Invesnow',
    logo: '/images/careers/invesnow.png',
    location: 'Jakarta, Indonesia',
    location_type: 'On-site',
    type: 'Fulltime',
    start_date: '2020-01',
    end_date: '2021-01',
    industry: 'financing',
    link: 'https://invesnow.id',
  },
  {
    position: 'Full Stack Developer',
    company: 'UNSIKA',
    logo: '/images/careers/unsika.png',
    location: 'Karawang, Indonesia',
    location_type: 'On-site',
    type: 'Full-time',
    start_date: '2019-02',
    end_date: '2020-12',
    industry: 'school',
    link: 'https://www.unsika.ac.id',
  },
  {
    position: 'Full Stack Developer',
    company: 'Otscon Inc',
    logo: '/images/careers/otscon.png',
    location: 'Karawang, Indonesia',
    location_type: 'Remote',
    type: 'Full-time',
    start_date: '2018-09',
    end_date: '2019-09',
    industry: 'otomotive',
    link: 'https://www.otscon.com',
  },
  {
    position: 'Software Engineer',
    company: 'Decodev',
    logo: '/images/careers/decodev.png',
    location: 'Karawang, Indonesia',
    location_type: 'Remote',
    type: 'Self-employed',
    start_date: '2017-03',
    end_date: '2019-02',
    industry: 'software house',
    link: 'https://decodev.id',
  },
];
